version: 2
jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: BasicCiCd
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: BasicCiCd/MyLibrary
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: BasicCiCd/MyLibrary.Test
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud