name: net-core-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: |
         dotnet build BasicCiCd/MyLibrary/MyLibrary.csproj --configuration Release
         nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/techs-blueprint/basic-ci-cd/index.json" -UserName techs-blueprint
         nuget pack
         nuget push "basic-ci-cd.net.1.0.0.nupkg" -Source "GitHub"